const Router = require('koa-router')
const router = new Router()
const user = require('./user.js')
const circle = require('./circle.js')
const friend = require('./friend.js')
const chat  = require('./chat.js')
const product = require('./product.js')
const score = require('./score.js')
const strategy = require('./strategy.js')
const album = require('./album.js')
router.use('/user',user.routes(),user.allowedMethods())
router.use('/circle',circle.routes(),circle.allowedMethods())
router.use('/friend',friend.routes(),friend.allowedMethods())
router.use('/chat',chat.routes(),chat.allowedMethods())
router.use('/product',product.routes(),product.allowedMethods())
router.use('/score',score.routes(),score.allowedMethods())
router.use('/strategy',strategy.routes(),strategy.allowedMethods())
router.use('/album',album.routes(),album.allowedMethods())
module.exports = router