const Router = require('koa-router')
const router = new Router()
const user = require('./user.js')
const circle = require('./circle.js')
const friend = require('./friend.js')
const chat  = require('./chat.js')
router.use('/user',user.routes(),user.allowedMethods())
router.use('/circle',circle.routes(),circle.allowedMethods())
router.use('/friend',friend.routes(),friend.allowedMethods())
router.use('/chat',chat.routes(),chat.allowedMethods())
module.exports = router